name: Build Docker

on:
  repository_dispatch:
    types: ["dispatch"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: SIEGFRIED_VERSION=v${{ github.event.client_payload.version }}
          tags: |
            ghcr.io/keeps/siegfried:v${{ github.event.client_payload.version }}
            ghcr.io/keeps/siegfried:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
